compania/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/', include('apps.gestionClientes.urls')),
    path('login/', include('apps.login.urls')),
    path('', views.index, name='homepage')
]

apps/modelo/models.py
from django.db import models


class Persona(models.Model):

    listaGenero = (
        ('femenino','Femenino'),
        ('masculino', 'Masculino')
    )

    persona_id = models.AutoField(primary_key = True)
    cedula = models.CharField(max_length = 10, null = False, unique = True)
    apellidos = models.CharField(max_length = 70, null = False)
    nombres = models.CharField(max_length = 70, null = False)
    genero = models.CharField(max_length = 30, choices = listaGenero, default = 'femenino')
    correo = models.EmailField(max_length = 105)
    telefono = models.CharField(max_length = 15)
    celular = models.CharField(max_length = 15, null = False)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.cedula

class Barrio(models.Model):

    barrio_id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 100, null = False, unique = True)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.nombre

class Cliente(models.Model):

    cliente_id = models.AutoField(primary_key = True)
    calle1 = models.CharField(max_length = 100, null = True)
    calle2 = models.CharField(max_length = 100, null = True)
    referencia1 = models.CharField(max_length = 150, null = False)
    referencia2 = models.CharField(max_length = 150, null = True)
    barrio = models.ForeignKey(Barrio, on_delete = models.CASCADE)
    persona = models.ForeignKey(Persona, on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.persona

class Agente(models.Model):

    listaFunciones = (
        ('chofer','Chofer'),
        ('call center', 'Call Center')
    )

    agente_id = models.AutoField(primary_key = True)
    funcion = models.CharField(max_length = 30, choices = listaFunciones, default = 'femenino')
    persona = models.ForeignKey(Persona, on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.persona

templates/callCenter/crearBarrio.html
{% extends "master.html" %}

{% block contenido %}
<br>
<h1 class="text-center">Crear Barrio</h1>
<form method="POST"> {% csrf_token %}
    <h4 class="font-weight-bold">Datos del Barrio:</h4>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_nombre">Nombre del Barrio:</label>
            <input type="text" class="form-control" name="nombre" maxlength="100" required id="id_nombres">
        </div>
    </div>
    <button type="submit" class="btn btn-success"> Crear Barrio </button>
</form>
<a class="btn btn-secondary" href="{% url 'gestion'%}" role="button">¿Volver?</a>
{% endblock %}

templates/callCenter/crearClientes.html
{% extends "master.html" %}

{% block contenido %}
<br>
<h1 class="text-center">Crear Cliente</h1>
<form method="POST"> {% csrf_token %}
    <br>
    <h2><strong>Barrio: </strong> {{barrio.nombre}}</h2>
    <br>
    <h4 class="font-weight-bold">Datos de la Persona:</h4>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_cedula">Cedula</label>
            <input type="text" class="form-control" name="cedula" maxlength="10" required id="id_cedula">
        </div>
        <div class="form-group col-md-4">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" name="apellidos" maxlength="70" required id="id_apellidos">
        </div>
        <div class="form-group col-md-4">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" name="nombres" maxlength="70" required id="id_nombres">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_genero">Genero:</label>
            <select name="genero" id="id_genero" class="form-control">
                <option value="femenino">Femenino</option>
                <option value="masculino">Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="id_correo">Correo:</label>
            <input type="email" class="form-control" name="correo" maxlength="105" required id="id_correo"></p>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_telefono">Telefono:</label>
            <input type="text" class="form-control" name="telefono" maxlength="15" required id="id_telefono">
        </div>
        <div class="form-group col-md-6">
            <label for="id_celular">Celular:</label>
            <input type="text" class="form-control" name="celular" maxlength="15" required id="id_celular">
        </div>
    </div>
    <h4><strong>Datos del Cliente:</strong></h4>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_calle1">Calle 1:</label>
            <input type="text" class="form-control" name="calle1" maxlength="100" required id="id_calle1">
        </div>
        <div class="form-group col-md-4">
            <label for="id_calle2">Calle 2:</label>
            <input type="text" class="form-control" name="calle2" maxlength="100" required id="id_calle2">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_referencia1">Referencia 1:</label>
            <input type="text" class="form-control" name="referencia1" maxlength="150" required id="id_referencia1">
        </div>
        <div class="form-group col-md-4">
            <label for="id_referencia2">Referencia 2:</label>
            <input type="text" class="form-control" name="referencia2" maxlength="150" required id="id_referencia2">
        </div>
    </div>
    <button type="submit" class="btn btn-success"> Crear Cliente </button>
</form>
<a class="btn btn-secondary" href="{% url 'barrios'%}" role="button">¿Volver?</a>
{% endblock %}

templates/callCenter/index.html
{% extends "master.html" %}
{% block contenido %}
<br>
<h1 class="text-center">Listado de Clientes</h1>
<a class="btn btn-primary" href="{% url 'barrios'%}" role="button"> ¿Barrios? </a>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">Cédula</th>
            <th scope="col">Apellidos y Nombres</th>
            <th scope="col">Barrio</th>
            <th scope="col">Calle 1</th>
            <th scope="col">Calle 2</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cliente in listaClientes%}
        <tr class="table-secondary text-dark">
            <td><a href="{% url 'modificar_cliente' cliente.cliente_id %}">{{cliente.persona.cedula}}</a></td>
            <td>{{cliente.persona.apellidos}} {{cliente.persona.nombres}}</td>
            <td>{{cliente.barrio.nombre}}</td>
            <td>{{cliente.calle1}}</td>
            <td>{{cliente.calle2}}</td>
            <td>
                <a class="btn btn-danger" href="{% url 'eliminar_cliente' cliente.cliente_id %}" role="button"> Eliminar
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/callCenter/indexBarrios.html
{% extends "master.html" %}
{% block contenido %}
<br>
<h1 class="text-center">Listado de Barrios</h1>
<a class="btn btn-primary" href="{% url 'crear_barrio'%}" role="button"> ¿Nuevo Barrio? </a>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">Barrio</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for barrio in listaBarrios%}
        <tr class="table-secondary text-dark">
            <td><a href="{% url 'modificar_barrio' barrio.barrio_id %}">{{barrio.nombre}}</a></td>
            <td>
                <a class="btn btn-success" href="{% url 'crear_cliente' barrio.barrio_id %}" role="button"> Añadir
                    Cliente
                </a>
                <a class="btn btn-danger" href="{% url 'eliminar_barrio' barrio.barrio_id %}" role="button"> Eliminar
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-secondary" href="{% url 'gestion' %}" role="button">¿Volver?</a>
{% endblock %}

templates/callCenter/modificarBarrio.html
{% extends "master.html" %}
{% block contenido %}
<br>
<h1 class="text-center">Modificar Barrio</h1>
<form method="POST"> {% csrf_token %}
    <h2 class="font-weight-bold">Datos del Barrio: </h2>
    <br>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_nombre">Nombre del Barrio:</label>
            <input type="text" class="form-control" name="nombre" maxlength="100" required id="id_nombre"
                value="{{ formulario_barrio.nombre.value }}">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Modificar Barrio</button>
</form>
<a class="btn btn-secondary" href="{% url 'barrios' %}" role="button">¿Volver?</a>
{% endblock %}

templates/callCenter/modificarCliente.html
{% extends "master.html" %}
{% block contenido %}
<br>
<h1 class="text-center">Modificar Cliente</h1>
<form method="POST"> {% csrf_token %}
    <h2 class="font-weight-bold">Datos de la Persona: </h2>
    <div class="form-row">
        <div class="form-group col-md-4">
            <h3><strong>Cédula:</strong> {{ formulario_persona.cedula.value }}</h3>
        </div>
        <div class="form-group col-md-4">
            <h2><strong>Barrio: </strong> {{ barrio.nombre }}</h2>
        </div>
    </div>

    <input type="hidden" class="form-control" name="cedula" maxlength="70" required id="id_apellidos"
        value="{{ formulario_persona.cedula.value }}">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" name="apellidos" maxlength="70" required id="id_apellidos"
                value="{{ formulario_persona.apellidos.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" name="nombres" maxlength="70" required id="id_nombres"
                value="{{ formulario_persona.nombres.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_genero">Genero:</label>
            <select name="genero" id="id_genero" class="form-control">
                {% if formulario_persona.genero.value == 'femenino' %}
                <option value="femenino" selected>Femenino</option>
                <option value="masculino">Masculino</option>
                {% elif formulario_persona.genero.value == 'masculino' %}
                <option value="femenino">Femenino</option>
                <option value="masculino" selected>Masculino</option>
                {% endif %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="id_correo">Correo:</label>
        <input type="email" class="form-control" name="correo" maxlength="105" required id="id_correo"
            value="{{ formulario_persona.correo.value }}">
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_telefono">Telefono:</label>
            <input type="text" class="form-control" name="telefono" maxlength="15" required id="id_telefono"
                value="{{ formulario_persona.telefono.value }}">
        </div>
        <div class="form-group col-md-6">
            <label for="id_celular">Celular:</label>
            <input type="text" class="form-control" name="celular" maxlength="15" required id="id_celular"
                value="{{ formulario_persona.celular.value }}">
        </div>
    </div>
    <h2 class="font-weight-bold">Datos del Cliente: </h2>
    <br>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_calle1">Calle 1:</label>
            <input type="text" class="form-control" name="calle1" maxlength="150" required id="id_calle1"
                value=" {{ formulario_cliente.calle1.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_calle2">Calle 2:</label>
            <input type="text" class="form-control" name="calle2" maxlength="150" required id="id_calle2"
                value=" {{ formulario_cliente.calle2.value }}">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_referencia1">Referencia 1:</label>
            <input type="text" class="form-control" name="referencia1" maxlength="150" required id="id_referencia1"
                value=" {{ formulario_cliente.referencia1.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_referencia2">Referencia 2:</label>
            <input type="text" class="form-control" name="referencia2" maxlength="150" required id="id_referencia2"
                value=" {{ formulario_cliente.referencia2.value }}">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Modificar Cliente</button>
</form>
<a class="btn btn-secondary" href="{% url 'gestion' %}" role="button">¿Volver?</a>
{% endblock %}